---

- name: scan environment
  service_facts:
  register: services_state
- debug: var=services_state.ansible_facts.services["docker.service"].state
- debug: var=services_state.ansible_facts.services["nexus.service"].state

  
- name: check and install utils 
  yum:
    name: "{{ packages }}"
    state: present

- name: allow https connection
  firewalld:
    zone: public
    port: 443/tcp 
    permanent: yes
    state: enabled
          
- name: allow http connection
  firewalld:
    zone: public
    port: 80/tcp 
    permanent: yes
    state: enabled
  notify: firewall reload

- name: postfix start
  systemd:
    name: postfix
    state: started

- name: add gitlab repo
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
  args:
          warn: no

- name: install gitlab
  yum:
    name: gitlab-ce
    state: present

...
