version: '3'

services:

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - /home/gri/gitlab_ci/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gri/gitlab_ci/build:/srv/build
    restart: always
    network_mode: host
    extra_hosts: 
        - "grilab.io:192.168.0.33"
   
