---
# Run Gitlab & gitlab-runner

- hosts: localhost
  connection: local
  become: yes
  become_user: root

  roles:
  - role: ans-gitlab

  tasks:

  - name: gitlab-runner in container
    docker_compose:
      project_src: /home/gri/gitlab_runner

  - name: configure runner
    script: /home/gri/gitlab_runner/runner_registration.sh
    
    
...
