---
# Run Gitlab & gitlab-runner

- hosts: grilab.io
  connection: local
  become: yes
  become_user: root

  roles:
  - role: ans-gitlab

  tasks:

  - name: gitlab-runner in container
    docker_compose:
        project_src: /home/gri/gitlab_ci

    
...
