image: docker:latest

stages:
  - testing
  - packing
  - uploading  
  - checking

variables:
  IMAGE: grilab.io:8082/testwebapp

test:
  stage: testing
  script: cat index.html | grep '<title>WebApp</title>'

build:
  stage: packing
  script:
    - docker build -t $IMAGE .

upload:
  stage: uploading
  script:
    - docker login -u gri -p "$NEXUS_PASS" grilab.io:8082
    - docker push $IMAGE

check:
  stage: checking
  script:
    - docker login -u gri -p "$NEXUS_PASS" grilab.io:8082
    - docker pull $IMAGE

